### ISSUE TITLE
[Feature] Webhook filter with player names

### ISSUE THREAD

**Issue by Ktlist** [Plenyx/PlenBotLogUploader#2]
would be great to have a filter in each webhook to  only use that webhook if x amount of the players in a filter are present in the report

very useful to upload automatically to the proper guild discord based on the players you are currently raiding with

**Comment by Plenyx** [comment]
As far as I understand, you want to base the upload on how many players are within the log, however, you also mention to send the log via that to a proper guild based server, which you want it based on the account names? This mildly confuses me 🤣.

**Comment by Ktlist** [comment]
fair enough my explanation was a bit erratic sorry,

first of all when i said upload, i meant send the link to the discord webhook, uploading to dps.report is always asumed is done, this only refers tu the use of discord webhooks
my situation is that i do raids with several guilds that involve severall people, and i dont want to use the discord webhook of one guild if im not playing with them and also dont want to manage it manually creating sessions.

the solution: 
each webhook has another parameter, a filter, that is a list of player usernames i.e: ktlist.6879, lexin.1457, ....
before uploading to a webhook checks the report and compares the list in the filter with the list of players in the report,
if it matches then it uses the webhook, if not, it doesn´t, 
the filter is only used if not empty, and the webhook is active, if its active and there is no filter it  uploads it normally 

further improvements:
another variable (int) that especifies the minimum number of matches between filter and report to actually upload 
i.e:

>  
>      length of the filter: 15 people  
>      minimum matches variable (min): 5
>      if matches between filter and report is > min -> use webhook
>      if matches   "      "      "      "  "  < min -don´t use webhook 
> 

i hope this is more clear, but if not, that might very esaly be, ask again any doubt
and thanks for a very great job
