### ISSUE TITLE
CI always spinns up two instances for PR pushes

### ISSUE THREAD

**Issue by SaculRennorb** [Plenyx/PlenBotLogUploader#25]
![iamge](https://user-images.githubusercontent.com/18741506/203883405-9c8be3a9-7ce8-41be-a3e9-396776033da1.png)

See image above, this always happens. Reasonably low prio imo, but maybe look at it.

**Comment by sobrinth** [comment]
Thanks for pointing this out. It will no longer happen on future PRs
