### ISSUE TITLE
Set an Team to Aleeva integration is not saved

### ISSUE THREAD

**Issue by cedvan** [Plenyx/PlenBotLogUploader#29]
Hi,

Set an Team to Aleeva integration is not saved, and all aleeva integrations stay with "No team" configuration.
So PlenBot send dps report to all aleeva integration and so to all channels :/

Issue linked : https://github.com/HardstuckGuild/PlenBotLogUploader/issues/6

**Comment by Plenyx** [comment]
Fixed in 34b6d72cac9e20caa8768cc87e1bd1a523611fa8
