### ISSUE TITLE
Log sync

### ISSUE THREAD

**Issue by ClaytonAstrom** [Plenyx/PlenBotLogUploader#31]
I'm using Aleeva and dps.report triggers.  Sometimes I notice that dps.report will fail, and this will prevent Aleeva from triggering.  I know this is a huge ask but is it possible to add sync type tasks alongside triggers?  That way if there's a failure or plenbot wasn't running it can "catch up" on previous logs detected in the filesystem

GW2Wingman is a good example of this.

**Comment by Plenyx** [comment]
I have added a simple reupload for logs that failed to upload. Doing a system that detects logs if the upload was not running would be a very demanding task to calculate. I want to add an additional commit that would enable this type of feature, but it would be disabled by default (the user would have to opt in).

**Comment by ClaytonAstrom** [comment]
Yeah that makes sense, I appreciate you looking into it!  Thanks!

**Comment by Plenyx** [comment]
Hello. Sorry for such a late reply. I tried to include the addition I talked about but I have encountered a problem of being very rate limited by dps.report. Additionally, few viewers of mine also brought up the issue of corrupted logs which I did properly not include in the reupload. I will not be able to slot the fully proposed change into the next release that I plan on releasing on 27th but I will try to resolve the issues by the next release. Sorry for the inconvenience.

**Comment by Plenyx** [comment]
Hi. I looked into it again. I will close this issue. The current implementation is not a full reupload but it still solves the issues of reuploading logs when there were errors on dps.report end. I will stay by what I said before that the task to detect which logs have been uploaded already would be a big computation task that would have to be run every time and I do not think it should be a part of the uploader unless I find a solution that would not be as demanding.
