### ISSUE TITLE
Nexus + ArcDPS support

### ISSUE THREAD

**Issue by DeltaRaidcore** [Plenyx/PlenBotLogUploader#41]
When installing Nexus+Arcdps the configuration should be the following:

- `<GW2>/d3d11.dll` (Nexus)
- `<GW2>/addons/arcdps.dll` (ArcDPS, naming of dll does not matter)
- `<GW2>/addons/someArcPlugin.dll` (ArcDPS plugins should be placed with it into /addons, /bin64 or the main directory. /addons is preferred)

This **prevents double installations of ArcDPS** as most Nexus users won't chainload it, but at the moment PlenBot will install ArcDPS as the chainload.
You can also probe which .dll is ArcDPS by checking `File description == "arcdps"` and then continue using the existing configuration.

**Comment by Plenyx** [comment]
Hey Delta, sorry for the late reply. Did I understand the fix correctly? I think I only needed to change df39feb784f95f8fa897cd78741b321e265afd0c and nothing else.

**Comment by DeltaRaidcore** [comment]
Yes, that's correct. Does this also affect where arc's plugins are to be installed?
Because they have to be either in `<GW2>/bin64`, the root directory or alongside arcdps which is then `<GW2>/addons`.
Latter would be the cleanest imo

**Comment by Plenyx** [comment]
I have a quick question: Does ardps load them by default if they are in the addons folder? Currently, all dlls are all in the root folder.

**Comment by DeltaRaidcore** [comment]
ArcDPS checks:
- GW2 Root
- `<GW2>/bin64`
- and wherever it is located itself

So not by default.
