### ISSUE TITLE
arcdps plugin manager invalid updates

### ISSUE THREAD

**Issue by bbck** [Plenyx/PlenBotLogUploader#43]
Recently in the past few days PlenBot has updated d3d11.dll with a new version of arc, except the file downloaded was not arcdps but a 1 KB file with the contents `error code: 522`. 

If I manually go to deltaconnected.com I do get a Cloudflare 522 error page, but PlenBot should probably be smart enough to not download the invalid dll.

![image](https://github.com/Plenyx/PlenBotLogUploader/assets/154447/9e2b5a0c-ce15-4022-a222-ad5e3c9bf14f)

**Comment by Plenyx** [comment]
Hello @bbck. I have also noticed a similar problem. There is a planned fix for the next release. I will reference the commits as they come up.
