### ISSUE TITLE
[BUG] ArcDPS WvW Healing/Barrier Summary discrepancy

### ISSUE THREAD

**Issue by 0dr** [Plenyx/PlenBotLogUploader#45]
## Description
When using the upload and summarise function for Discord, there are discrepancies in the values for the healing/barrier sum, when compared to the report.DPS log, when played in WvW and with longer fights.

I've noticed almost double the reported values when compared to the HTML report.

## Speculation 
We have values for TotalHealing and TotalHealingOnAllies, later doesn't seem to properly work in WvW.
I couldn't check if they are minions and other entries or actual players.

## TMP fix
When using the TotalHealing values from the report, the values for Healing match those of the HTML report.
https://github.com/0dr/PlenBotLogUploader/commit/66bfcb92538b3e1f4b616f0bb28f0c72e7115c30

**Comment by Plenyx** [comment]
Hello there. Thank you for reporting this. Can you maybe link me a picture of the result and the log so I cna diagnose what might have caused it? It is weird it doesn't match up, I will be asking around about the extra json output of EI.

**Comment by 0dr** [comment]
https://dps.report/w.report/TvUA-20240818-164614_wvw

![Sample 2](https://github.com/user-attachments/assets/986db0ac-5066-4f98-93c3-c0fc971922a5)

(The log but from a different users perspective) 
[20240818-164614.zip](https://github.com/user-attachments/files/16732759/20240818-164614.zip)
