### ISSUE TITLE
Remote Pings

### ISSUE THREAD

**Issue by thisSyntax** [Plenyx/PlenBotLogUploader#46]
While the function of Remote Server pings still works the only way to enable previously setup pings is to close out the application edit the remote_ping.json to set the isActive value to true then start the program again.  Not sure why the built in settings for this were removed.

**Comment by Plenyx** [comment]
Hello. This was an error on me, I have readded the access that I deleted by accident.
If you want to use the fix immediately, you can download it from here: https://github.com/Plenyx/PlenBotLogUploader/actions/runs/11095296052
