### ISSUE TITLE
.NET core v6

### ISSUE THREAD

**Issue by Plenyx** [Plenyx/PlenBotLogUploader#5]
Switch to .NET core v6 planned for Release 75.

As a developer, I want to use the latest (safety) features of .NET core v6 in this project.

This change would require an extensive rewrite into existing components to be compatible for transfer from .NET Standard to .NET Core.

### Goals for the migration:

- [x] Use .NET 6
- [x] Find replacement for ILMerge -> Single file publishing
- [x] Use Github-Actions to build PlenBotLogUploader (integration and release)
- [x] Make sure all features work after the transition
- [x] Make sure auto-update still works

[Upgrade tool](https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-winforms-framework)

**Comment by SamMackrill** [comment]
I have done a few of these upgrades now (from .net framework 4.7.2 + 4.8 mostly), let me know if you need a hand
