### ISSUE TITLE
Better management of send logs for aleeva/gw2bot

### ISSUE THREAD

**Issue by xfouloux** [Plenyx/PlenBotLogUploader#6]
Hi !
I would like to ask for an improvment, if possible =) !

It would be great if the Teams could be further improved to work with aleeva/gw2bot and not only with discord webhooks
The ability to do that would allow for autopost of logs in differents channels/discord depending on who you are with but with aleeva/gw2bot too.

As you can see having teams + the filters that already exists, but extended to these bots, would allow for more customization of where the autopost are sent, because most of the time people don't use the same discord/channel to post www and raid/strikes/fractals.

Thanks !

**Comment by Plenyx** [comment]
The main issue I didn't implement it initially is that both of the bots have single access for multiple outputs themselves. It would make the hopping between different Discord servers using the same bot very difficult. Nevertheless I think it is adequate to add it now, so it is consistent across all the modules.

**Comment by cedvan** [comment]
Hi @Plenyx, 

This feature don't work at this time. 
Set an Team to Aleeva integration is not saved, and all aleeva integrations stay with no team configuration. 
So PlenBot send dps report to all aleeva integration and so to all channels :/
